Vagrant.configure("2") do |config|
  config.vm.box = "aerospike/centos-6.5"
  config.vm.network "public_network"
  
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "700"
   end

config.vm.define "centnginx" do |centnginx|

   config.vm.provision "shell", inline: <<-SHELL
   sudo yum install nginx -y
   sudo service nginx start
   sudo chkconfig nginx enable
   SHELL
 end

  
config.vm.define "centtom" do |centtom|

    config.vm.provision "shell", inline: <<-SHELL
    sudo yum install java-1.8.0-openjdk.x86_64 -y
    sudo yum install tomcat -y
    sudo service tomcat start
   SHELL
 end


config.vm.define "centmysql" do |centmysql|
 
     config.vm.provision "shell", inline: <<-SHELL
     sudo yum update
     sudo yum install -y mysql-server
     sudo service mysqld start
     sudo chkconfig mysqld on
   SHELL
 end
end
