Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos|
  centos.vm.box ="ubuntu/trusty64"
  centos.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    mkdir /home/vagrant/test
    touch /home/vagrant/test/file1
    SHELL
   end 
end
