Vagrant.configure ("2") do |config|
 config.vm.box = "aerospike/centos-6.5"
 config.vm.network "public_network"

  config.vm.define "nginux" do |nginx|
  nginx.vm.hostname = 'cennginx'

   config.vm.provision "shell", inline: <<-SHELL
    sudo yum install epel-release
    sudo yum install -y nginx
    sudo service nginx start
    sudo service nginx status
    sudo chkconfig nginx on
   SHELL
  end

  config.vm.define "httpd" do |httpd|
  httpd.vm.hostname = 'cenhttpd'
  
   config.vm.provider "virtualbox" do |vb|
   vb.memory ="1240"

    config.vm.provision "shell", inline: <<-SHELL
    sudo yum install epel-release
    sudo yum install -y httpd*
    sudo service httpd start
    sudo service httpd status
    sudo chkconfig httpd on
   SHELL
  end
 end

   config.vm.define "mysql" do |mysql|
   mysql.vm.hostname = 'cenmysql'

     config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"

    config.vm.provision "shell", inline: <<-SHELL
   sudo  yum install epel-release
   sudo  yum install -y mysql-server
   sudo  service mysqld start
   sudo  service mysqld status
   sudo  chkconfig mysqld on
   SHELL
  end
 end
end


