Vagrant.configure("2") do |config|
   config.vm.network "public_network"

 config.vm.define "centos" do |centos|
   centos.vm.box = "aerospike/centos-6.5"
   centos.vm.hostname = 'centos'

config.vm.provider "virtualbox" do |vb|
  vb.memory = "2564"
  end
end

 config.vm.define "scotch" do |scotch|
  scotch.vm.box = "scotch/box"
  scotch.vm.hostname = 'scotch'
 end

end
